export default {
  ACCOUNT_REQUEST: 'ACCOUNT_REQUEST',
  ACCOUNT_SUBMIT: 'ACCOUNT_SUBMIT',
  ACCOUNT_SUCCESS: 'ACCOUNT_SUCCESS',
  ACCOUNT_RECEIVE: 'ACCOUNT_RECEIVE',
  ACCOUNT_ERROR: 'ACCOUNT_ERROR'
};
