export default {
  USER_AUTHENTICATED: 'USER_AUTHENTICATED',
  USER_UNAUTHENTICATED: 'USER_UNAUTHENTICATED',
  AUTH_USER_REQUEST: 'AUTH_USER_REQUEST',
  AUTH_USER_RECEIVE: 'AUTH_USER_RECEIVE',
  AUTH_ACCOUNT_REQUEST: 'AUTH_ACCOUNT_REQUEST',
  AUTH_ACCOUNT_RECEIVE: 'AUTH_ACCOUNT_RECEIVE',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
};
